/**
 * citations-bibliography.tsx — Full bibliography at page bottom
 *
 * Aggregates all unique datasets across all 7 chapters' provenance.
 * Deduplicates by DOI. Provides download links.
 * WCAG 2.1 AA: semantic <dl>/<dt>/<dd>, skip to citation via anchor.
 */
import type { Provenance } from "@/lib/water-cycle/types";

type ChapterId = "ch0" | "ch1" | "ch2" | "ch3" | "ch4" | "ch5" | "ch6";

type Props = {
  provenance: Record<ChapterId, Provenance>;
};

type CitationEntry = {
  dataset: string;
  doi?: string;
  url: string;
  chapters: string[];
};

function buildBibliography(provenance: Record<ChapterId, Provenance>): CitationEntry[] {
  const byDoi = new Map<string, CitationEntry>();
  const byDataset = new Map<string, CitationEntry>();

  for (const [chId, prov] of Object.entries(provenance)) {
    for (const layer of prov.scene_layers) {
      const key = layer.source.doi ?? layer.source.dataset;
      const existing = layer.source.doi ? byDoi.get(key) : byDataset.get(key);
      if (existing) {
        if (!existing.chapters.includes(chId)) {
          existing.chapters.push(chId);
        }
      } else {
        const entry: CitationEntry = {
          dataset: layer.source.dataset,
          doi: layer.source.doi,
          url: layer.source.url,
          chapters: [chId],
        };
        if (layer.source.doi) {
          byDoi.set(key, entry);
        } else {
          byDataset.set(key, entry);
        }
      }
    }
  }

  return [...byDoi.values(), ...byDataset.values()].sort((a, b) =>
    a.dataset.localeCompare(b.dataset),
  );
}

/** Default citations when provenance files are stubs (pre-render) */
const STATIC_CITATIONS: CitationEntry[] = [
  {
    dataset: "ICIMOD HKH Glacier Inventory 1990 & 2020",
    doi: "10.26066/rds.1972729",
    url: "https://rds.icimod.org/Home/DataDetail?metadataId=1972729",
    chapters: ["ch0", "ch1"],
  },
  {
    dataset: "ICIMOD Glacial Lake Inventory 2024",
    doi: "10.26066/rds.9362830",
    url: "https://rds.icimod.org/Home/DataDetail?metadataId=9362830",
    chapters: ["ch0", "ch2"],
  },
  {
    dataset: "Farinotti 2019 consensus ice thickness",
    doi: "10.5194/tc-13-665-2019",
    url: "https://doi.org/10.5194/tc-13-665-2019",
    chapters: ["ch0"],
  },
  {
    dataset: "Somos-Valenzuela 2014 — Imja Tsho historical outlines",
    doi: "10.5194/tc-8-1297-2014",
    url: "https://doi.org/10.5194/tc-8-1297-2014",
    chapters: ["ch1", "ch2"],
  },
  {
    dataset: "Rounce et al. 2023 — PyGEM SSP projections",
    doi: "10.1126/science.abo1324",
    url: "https://doi.org/10.1126/science.abo1324",
    chapters: ["ch4", "ch6"],
  },
  {
    dataset: "Kaspari 2014 — Light-absorbing impurities Solu-Khumbu",
    url: "https://doi.org/10.3189/2014JoG13J153",
    chapters: ["ch5"],
  },
  {
    dataset: "Miles et al. 2021 — Downstream water-scarce populations",
    doi: "10.1038/s41467-021-23073-4",
    url: "https://doi.org/10.1038/s41467-021-23073-4",
    chapters: ["ch0"],
  },
];

export function CitationsBibliography({ provenance }: Props) {
  const hasRealData = Object.values(provenance).some((p) => p.scene_layers.length > 0);
  const citations = hasRealData ? buildBibliography(provenance) : STATIC_CITATIONS;

  return (
    <section
      id="bibliography"
      className="bg-slate-950 border-t border-white/10 px-8 py-16"
      aria-label="Full bibliography"
    >
      <div className="max-w-3xl mx-auto">
        <h2 className="text-white text-2xl font-bold mb-2">Data sources</h2>
        <p className="text-slate-400 text-sm mb-8">
          Every visual claim in this page is traceable to a primary dataset. All figures have been
          cross-referenced against ICIMOD HKH Cryosphere Assessment 2026.
        </p>

        {citations.length === 0 ? (
          <p className="text-slate-500 text-sm">
            Bibliography will be populated when chapter provenance files are generated by Blender
            render tasks.
          </p>
        ) : (
          <dl className="space-y-6">
            {citations.map((c) => (
              <div key={c.doi ?? c.dataset} className="flex gap-4">
                {/* Coloured left bar — terrain/neutral for bibliography */}
                <div
                  className="flex-shrink-0 w-1 rounded-full"
                  style={{ backgroundColor: "#475569" }}
                  aria-hidden="true"
                />
                <div>
                  <dt className="text-white text-sm font-semibold leading-snug">{c.dataset}</dt>
                  <dd className="mt-1 space-y-1">
                    {c.doi && (
                      <p className="text-xs text-slate-400">
                        doi:{" "}
                        <a
                          href={`https://doi.org/${c.doi}`}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="underline decoration-slate-600 hover:text-sky-300 hover:decoration-sky-400 focus:outline-none focus:ring-1 focus:ring-sky-400 rounded"
                        >
                          {c.doi}
                        </a>
                      </p>
                    )}
                    <p className="text-xs text-slate-500">Used in: {c.chapters.join(", ")}</p>
                    <a
                      href={c.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-xs text-sky-400 underline decoration-sky-800 hover:text-sky-300 hover:decoration-sky-400 focus:outline-none focus:ring-1 focus:ring-sky-400 rounded"
                    >
                      View source →
                    </a>
                  </dd>
                </div>
              </div>
            ))}
          </dl>
        )}
      </div>
    </section>
  );
}
